GridWorld-Simple-v0:
  n_timesteps: 100000
  policy: 'MlpPolicy'
  learning_rate: 0.0001
  buffer_size: 100000
  learning_starts: 1000
  batch_size: 32
  tau: 1.0
  gamma: 0.99
  train_freq: 4
  gradient_steps: 1
  target_update_interval: 1000
  exploration_fraction: 0.1
  exploration_initial_eps: 1.0
  exploration_final_eps: 0.05

GridWorld-MovingGoals-v0:
  n_timesteps: 200000
  policy: 'MlpPolicy'
  learning_rate: 0.0001
  buffer_size: 100000
  learning_starts: 5000
  batch_size: 32
  gamma: 0.99
  exploration_fraction: 0.2
  exploration_final_eps: 0.05

GridWorld-MovingObstacles-v0:
  n_timesteps: 200000
  policy: 'MlpPolicy'
  learning_rate: 0.0001
  buffer_size: 100000
  batch_size: 32
  gamma: 0.99
  exploration_fraction: 0.2

GridWorld-FullDynamic-v0:
  n_timesteps: 300000
  policy: 'MlpPolicy'
  learning_rate: 0.0001
  buffer_size: 150000
  batch_size: 64
  gamma: 0.99
  exploration_fraction: 0.25
  exploration_final_eps: 0.05

